[build]
  publish = "."
  command = "npm run build"
  functions = "dist/netlify/functions"

[functions]
  node_bundler = "none"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"