[build]
  publish = "."
  functions = "netlify/functions"
  command = ""  # no build needed for a static site

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"
  # optional but fine:
  # external_node_modules = ["resend"]

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"